name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: pytest-main  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10.x']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          # dev dependencies for linting and coverage
          pip install black isort flake8 pytest-cov

      - name: Check import sorting with isort
        run: isort . --profile black --check-only

      - name: Check code formatting with black
        run: black . --check

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests with coverage
        run: pytest --maxfail=1 --disable-warnings -q --cov=. --cov-report=term-missing --cov-fail-under=80
